### PR TITLE
Fix related to scoped releases

### LINKED ISSUE #63: Scoped package support & bug fixes
I have a scoped package in the public npm registry: `@brianc/http` (creative name, I know) [link to npm here](https://www.npmjs.com/package/@brianc/http)

I am running `jspm install npm:@brianc/http` and getting the following:

```
err Repo npm:@brianc/http not found!

```

What am I doing wrong? :(

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes #63 

Has an oblique hat-tip around confusion when jspm conventions live in npm packages.

@guybedford didn't anguish over this warning message, let me know if you want/have some zippier wording

### CODE REVIEW

File: npm.js [hunk 1]
```diff
@@ -305,11 +309,16 @@ NPMLocation.prototype = {
     })
     .then(function(response) {
       // save lookupCache
-      if (newLookup)
-        return asp(fs.writeFile)(path.resolve(self.tmpDir, repo + '.json'), JSON.stringify(lookupCache))
+      if (newLookup) {
+        var lookupJSON = JSON.stringify(lookupCache);
+        var outputPath = path.resolve(self.tmpDir, repo + '.json');
+        return asp(mkdirp)(path.dirname(outputPath)).then(function() {
```
Comment (guybedford) [inline npm.js]: .then on a newline please.

**Comment by guybedford** [comment]
:+1:
